---
- block:
    - name: Update cache, upgrade, autoremove, autoclean
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: true
        autoclean: true
        clean: true
        
    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Rebooting after upgrade"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: reboot_required.stat.exists

  always:
    - name: Ensure apt locks are released
      ansible.builtin.file:
        path: /var/lib/dpkg/lock
        state: absent
      ignore_errors: yes

    - name: Ensure apt lists are in a clean state
      ansible.builtin.apt:
        clean: true
